spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportaldb
    username: root
    password: moneyheist

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: 'ec1a78efca5d5b3c20a0ca0e1c868150924cfa900bf9357fd74b17755ea37db6'
  expiration-time: '432000000'